apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  mongodb-root-username: rootadmin
  mongodb-root-password: ProdRootPass-2026-Strong
  mongodb-app-username: taskapp
  mongodb-app-password: ProdTaskPass-2026-Strong
  mongodb-database: three-tier-tasks
  mongodb-uri: mongodb://taskapp:ProdTaskPass-2026-Strong@mongodb-0.mongodb:27017/three-tier-tasks?authSource=three-tier-tasks
