apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
data:
  init-mongo.sh: |
    #!/bin/sh
    set -eu
    mongosh "mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@localhost:27017/admin" <<EOF
    db = db.getSiblingDB("$MONGO_INITDB_DATABASE");
    if (db.getUser("$MONGO_APP_USERNAME") === null) {
      db.createUser({
        user: "$MONGO_APP_USERNAME",
        pwd: "$MONGO_APP_PASSWORD",
        roles: [
          {
            role: "readWrite",
            db: "$MONGO_INITDB_DATABASE"
          }
        ]
      });
    }
    EOF
