apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-3tier-workloads-prod
  namespace: argocd
spec:
  project: eks-3tier
  source:
    repoURL: https://github.com/shiva/eks-3tier-devops-project.git
    targetRevision: HEAD
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: three-tier-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
