apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-3tier-root-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shiva/eks-3tier-devops-project.git
    targetRevision: HEAD
    path: argocd/apps/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
