apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-dev
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - three-tier-dev
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
