grafana:
  adminPassword: DevGrafanaPass-2026-Strong
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.dev.eks-3tier.internal
    path: /
    pathType: Prefix
  defaultDashboardsTimezone: browser
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
prometheus:
  prometheusSpec:
    retention: 10d
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: {}
alertmanager:
  alertmanagerSpec:
    replicas: 1
