apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccounts.yaml
  - storageclass.yaml
  - pdb.yaml
  - backend/configmap.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/hpa.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/hpa.yaml
  - mongodb/init-script-configmap.yaml
  - mongodb/service.yaml
  - mongodb/statefulset.yaml
  - ingress.yaml
