apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb
automountServiceAccountToken: false
